# Generated by Django 3.1.7 on 2021-04-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210415_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothes', 'clothes'), ('it', 'it'), ('electronics', 'electronics'), ('sports', 'sports')], default='it', max_length=200),
        ),
    ]
